name: Github pipe demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip
  Run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: sudo apt install wget
        #install chrome app
      - run: curl https://intoli.com/install-google-chrome.sh | bash
      - run: mv /usr/bin/google-chrome-stable /usr/bin/google-chrome
        #install chromeDriver
      - run: wget https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
      - run: unzip chromedriver_linux64.zip
      - run: sudo mv chromedriver /usr/bin/chromedriver
      - run: mvn test
